package top.mcocet.mMOAddon.foliafix.transformer;

import org.objectweb.asm.*;
import org.objectweb.asm.util.CheckClassAdapter;
import top.mcocet.mMOAddon.foliafix.target.PluginTarget;

import java.lang.instrument.ClassFileTransformer;
import java.security.ProtectionDomain;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * ASM ClassFileTransformer that modifies scheduler calls in MythicLib / MMOItems classes
 * to be Folia-compatible.
 *
 * All Bukkit.getScheduler() calls inside configured target packages are redirected to
 * SchedulerHelper.getScheduler(), which returns a proxy that routes legacy scheduler calls
 * to Folia's GlobalRegionScheduler / AsyncScheduler.
 *
 * BukkitRunnable.runXxx(plugin, ...) calls are also patched directly so that the returned
 * BukkitTask can be properly cancelled.
 */
public class FoliaSchedulerTransformer implements ClassFileTransformer {

    private static final Logger LOGGER = Logger.getLogger("MMOAddon-FoliaFix");
    private static final String HELPER_CLASS = "top/mcocet/mMOAddon/foliafix/common/SchedulerHelper";
    private static final String BUKKIT_CLASS = "org/bukkit/Bukkit";
    private static final String BUKKIT_SCHEDULER_CLASS = "org/bukkit/scheduler/BukkitScheduler";
    private static final String BUKKIT_RUNNABLE_CLASS = "org/bukkit/scheduler/BukkitRunnable";

    private static int transformCallCount = 0;
    private static int schedulerPatchCount = 0;
    private static int bukkitRunnablePatchCount = 0;

    /**
     * Active target package prefixes (slash-form) used by this transformer.
     * Updated by FoliaSchedulerPatcher based on which plugins are actually loaded.
     */
    private static volatile Set<String> activeSlashPrefixes = Collections.emptySet();

    public static void setActiveTargets(List<PluginTarget> targets) {
        Set<String> prefixes = new HashSet<>();
        for (PluginTarget target : targets) {
            prefixes.add(target.getSlashPackagePrefix());
        }
        activeSlashPrefixes = Collections.unmodifiableSet(prefixes);
    }

    public static String getDebugStats() {
        return "transformCalls=" + transformCallCount + ", schedulerPatches=" + schedulerPatchCount + ", bukkitRunnablePatches=" + bukkitRunnablePatchCount;
    }

    @Override
    public byte[] transform(ClassLoader loader, String className, Class<?> classBeingRedefined,
                            ProtectionDomain protectionDomain, byte[] classfileBuffer) {
        if (className == null) {
            return null;
        }

        // Only patch classes from active target plugins.
        if (!matchesAnyActivePrefix(className)) {
            return null;
        }

        // Skip Lambda classes - they cannot be retransformed.
        if (className.contains("$$Lambda")) {
            return null;
        }

        // Pre-scan: only transform classes that actually call Bukkit.getScheduler() / BukkitRunnable methods,
        // or classes that need other Folia compatibility workarounds (e.g. MythicGlowModule, SoundMechanic).
        // This avoids unnecessary transformation of unrelated classes.
        if (!isAlwaysTransformedClass(className) && !needsTransformation(classfileBuffer)) {
            return null;
        }

        transformCallCount++;

        try {
            ClassReader reader = new ClassReader(classfileBuffer);
            // Use COMPUTE_MAXS only. COMPUTE_FRAMES recomputes stack map frames and may call
            // getCommonSuperClass on classes referenced in the bytecode (e.g. optional plugin
            // classes like Holograms/CMI) that are not visible to the transforming classloader,
            // producing invalid frames and causing "class redefinition failed: invalid class".
            // Our patches only replace method invocations or linear method bodies, so the original
            // frames remain valid and COMPUTE_MAXS is sufficient.
            ClassWriter writer = new SafeClassWriter(reader, loader, ClassWriter.COMPUTE_MAXS);
            ClassVisitor checker = new CheckClassAdapter(writer, false);
            ClassVisitor visitor = new SchedulerClassVisitor(checker, className);
            reader.accept(visitor, ClassReader.EXPAND_FRAMES);
            byte[] bytes = writer.toByteArray();
            // Run an ASM check over the generated bytes to catch invalid bytecode before the JVM verifier sees it.
            try {
                new ClassReader(bytes).accept(new CheckClassAdapter(new ClassVisitor(Opcodes.ASM9) {}, false), ClassReader.SKIP_DEBUG);
            } catch (Exception checkEx) {
                LOGGER.log(Level.SEVERE, "[MMOAddon-FoliaFix] Generated bytecode failed ASM verification for " + className + ": " + checkEx.getMessage(), checkEx);
                return null;
            }
            return bytes;
        } catch (Exception e) {
            LOGGER.log(Level.WARNING, "[MMOAddon-FoliaFix] Failed to transform class " + className + ": " + e.getMessage(), e);
            return null;
        }
    }

    private static boolean matchesAnyActivePrefix(String className) {
        for (String prefix : activeSlashPrefixes) {
            if (className.startsWith(prefix)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Quickly scan the class bytes for Bukkit.getScheduler() or BukkitRunnable scheduler calls.
     * Returns true only if the class contains at least one target invocation.
     */
    private static boolean needsTransformation(byte[] classfileBuffer) {
        try {
            ClassReader reader = new ClassReader(classfileBuffer);
            reader.accept(new ClassVisitor(Opcodes.ASM9) {
                @Override
                public void visit(int version, int access, String name, String signature, String superName, String[] interfaces) {
                    // Anonymous inner classes that extend BukkitRunnable need transformation
                    // because their runTaskXxx calls may not reference BukkitRunnable as owner.
                    if (BUKKIT_RUNNABLE_CLASS.equals(superName)) {
                        throw new FoundException();
                    }
                }

                @Override
                public MethodVisitor visitMethod(int access, String name, String descriptor,
                                                 String signature, String[] exceptions) {
                    return new MethodVisitor(Opcodes.ASM9) {
                        @Override
                        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {
                            if (opcode == Opcodes.INVOKESTATIC
                                    && owner.equals(BUKKIT_CLASS)
                                    && name.equals("getScheduler")
                                    && descriptor.equals("()L" + BUKKIT_SCHEDULER_CLASS + ";")) {
                                throw new FoundException();
                            }
                            if (opcode == Opcodes.INVOKEVIRTUAL
                                    && isBukkitRunnableSchedulerName(name)
                                    && descriptor.startsWith("(Lorg/bukkit/plugin/Plugin;")) {
                                throw new FoundException();
                            }
                            // Paper 1.20.5+: Sound is an interface and no longer has valueOf.
                            if (opcode == Opcodes.INVOKESTATIC
                                    && owner.equals("org/bukkit/Sound")
                                    && name.equals("valueOf")
                                    && descriptor.equals("(Ljava/lang/String;)Lorg/bukkit/Sound;")) {
                                throw new FoundException();
                            }
                        }
                    };
                }
            }, ClassReader.SKIP_FRAMES | ClassReader.SKIP_DEBUG);
        } catch (FoundException e) {
            return true;
        } catch (Exception e) {
            // If scanning fails, assume transformation is needed to be safe.
            return true;
        }
        return false;
    }

    private static boolean isBukkitRunnableSchedulerName(String name) {
        return "runTask".equals(name)
                || "runTaskLater".equals(name)
                || "runTaskTimer".equals(name)
                || "runTaskAsynchronously".equals(name)
                || "runTaskLaterAsynchronously".equals(name)
                || "runTaskTimerAsynchronously".equals(name);
    }

    /**
     * Classes that must always be transformed even if they do not call Bukkit.getScheduler().
     * These classes need other Folia / Paper 1.20.5+ compatibility workarounds.
     */
    private static boolean isAlwaysTransformedClass(String className) {
        return "io/lumine/mythic/lib/glow/provided/MythicGlowModule".equals(className)
                || "io/lumine/mythic/lib/util/SoundObject".equals(className)
                || "io/lumine/mythic/lib/hologram/factory/BukkitHologramFactory$HologramImpl".equals(className)
                || "io/lumine/mythic/lib/hologram/factory/LegacyBukkitHologramFactory$HologramImpl".equals(className);
    }

    /**
     * Checks whether the given ASM owner is a class from one of the active target plugins
     * (used when patching BukkitRunnable.cancel() on subclasses).
     */
    private static boolean isActiveTargetOwner(String owner) {
        if (owner == null) {
            return false;
        }
        for (String prefix : activeSlashPrefixes) {
            if (owner.startsWith(prefix)) {
                return true;
            }
        }
        return false;
    }

    private static class FoundException extends RuntimeException {
        private static final long serialVersionUID = 1L;
    }

    private static class SafeClassWriter extends ClassWriter {
        private final ClassLoader classLoader;

        public SafeClassWriter(ClassReader reader, ClassLoader classLoader, int flags) {
            super(reader, flags);
            this.classLoader = classLoader;
        }

        @Override
        protected String getCommonSuperClass(String type1, String type2) {
            try {
                return super.getCommonSuperClass(type1, type2);
            } catch (TypeNotPresentException e) {
                return "java/lang/Object";
            }
        }
    }

    private static class SchedulerClassVisitor extends ClassVisitor {

        private final String className;
        private final boolean isMythicGlowModule;
        private final boolean isSoundMechanic;
        private final boolean isPlayerSoundMechanic;
        private final boolean isBukkitHologramFactory;
        private final boolean isLegacyBukkitHologramFactory;
        private final boolean isMMOPlayerData;

        public SchedulerClassVisitor(ClassVisitor cv, String className) {
            super(Opcodes.ASM9, cv);
            this.className = className;
            this.isMythicGlowModule = "io/lumine/mythic/lib/glow/provided/MythicGlowModule".equals(className);
            this.isSoundMechanic = "io/lumine/mythic/lib/script/mechanic/visual/SoundMechanic".equals(className);
            this.isPlayerSoundMechanic = "io/lumine/mythic/lib/script/mechanic/visual/PlayerSoundMechanic".equals(className);
            this.isBukkitHologramFactory = "io/lumine/mythic/lib/hologram/factory/BukkitHologramFactory".equals(className)
                    || "io/lumine/mythic/lib/hologram/factory/BukkitHologramFactory$HologramImpl".equals(className);
            this.isLegacyBukkitHologramFactory = "io/lumine/mythic/lib/hologram/factory/LegacyBukkitHologramFactory".equals(className)
                    || "io/lumine/mythic/lib/hologram/factory/LegacyBukkitHologramFactory$HologramImpl".equals(className);
            this.isMMOPlayerData = "io/lumine/mythic/lib/api/player/MMOPlayerData".equals(className);
        }

        @Override
        public MethodVisitor visitMethod(int access, String name, String descriptor,
                                         String signature, String[] exceptions) {
            MethodVisitor mv = super.visitMethod(access, name, descriptor, signature, exceptions);

            // On Folia, MythicGlowModule's scoreboard team registration is not supported.
            // We empty out the body of enable/disable/setGlowing/disableGlowing to prevent
            // UnsupportedOperationException from CraftScoreboard.registerNewTeam().
            if (isMythicGlowModule && isGlowModuleBlockedMethod(name, descriptor)) {
                return new EmptyBodyMethodVisitor(mv);
            }

            // On Paper 1.20.5+, org.bukkit.Sound is an interface instead of an enum.
            // SoundMechanic/PlayerSoundMechanic constructors use Sound.values()/Enum::name lambda
            // which fails with LambdaConversionException. Rewrite constructors to skip Sound.valueOf
            // and leave this.sound as null; cast() will fall back to soundString.
            if (isSoundMechanic && "<init>".equals(name)
                    && "(Lio/lumine/mythic/lib/util/configobject/ConfigObject;)V".equals(descriptor)) {
                return new SoundMechanicInitRewriter(mv);
            }
            if (isPlayerSoundMechanic && "<init>".equals(name)
                    && "(Lio/lumine/mythic/lib/util/configobject/ConfigObject;)V".equals(descriptor)) {
                return new PlayerSoundMechanicInitRewriter(mv);
            }

            // BukkitHologramFactory Folia patches.
            if (isBukkitHologramFactory) {
                // On Folia, clearPreviousEntities() iterates over all worlds and removes TextDisplay
                // entities from the GlobalRegionScheduler task created in the constructor. That
                // triggers "Accessing entity state off owning region's thread". Emptying it is safe:
                // it only cleans up stray holograms from previous crashes.
                if ("clearPreviousEntities".equals(name) && "()V".equals(descriptor)) {
                    return new EmptyBodyMethodVisitor(mv);
                }

                // updateLocation() teleports TextDisplays synchronously. On Folia region threads,
                // synchronous Entity.teleport() is disabled; use teleportAsync() instead and discard
                // the returned CompletableFuture.
                if ("updateLocation".equals(name) && "(Lorg/bukkit/Location;)V".equals(descriptor)) {
                    return new HologramTeleportRewriter(new SchedulerMethodVisitor(mv));
                }
            }

            // LegacyBukkitHologramFactory has the same cross-world entity removal issue.
            if (isLegacyBukkitHologramFactory && "clearPreviousEntities".equals(name) && "()V".equals(descriptor)) {
                return new EmptyBodyMethodVisitor(mv);
            }

            // MMOPlayerData.forEach* methods iterate over all loaded player data and invoke a
            // Consumer. On Folia the Consumer may access player entity state, so dispatch each
            // call to the owning player's region thread.
            if (isMMOPlayerData && ("forEach".equals(name) || "forEachPlaying".equals(name) || "forEachOnline".equals(name))
                    && "(Ljava/util/function/Consumer;)V".equals(descriptor)) {
                return new MMOPlayerDataForEachRewriter(new SchedulerMethodVisitor(mv));
            }

            return new EntityTeleportRewriter(new SchedulerMethodVisitor(mv));
        }

        private static boolean isGlowModuleBlockedMethod(String name, String descriptor) {
            if ("enable".equals(name) || "disable".equals(name)) {
                return "()V".equals(descriptor);
            }
            if ("setGlowing".equals(name)) {
                return "(Lorg/bukkit/entity/Entity;Lorg/bukkit/ChatColor;)V".equals(descriptor);
            }
            if ("disableGlowing".equals(name)) {
                return "(Lorg/bukkit/entity/Entity;)V".equals(descriptor);
            }
            return false;
        }
    }

    /**
     * MethodVisitor that replaces the entire method body with a single RETURN instruction.
     * Used to disable methods that touch unsupported Folia APIs.
     */
    private static class EmptyBodyMethodVisitor extends MethodVisitor {

        public EmptyBodyMethodVisitor(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitCode() {
            mv.visitCode();
            mv.visitInsn(Opcodes.RETURN);
        }

        @Override
        public void visitInsn(int opcode) {}

        @Override
        public void visitIntInsn(int opcode, int operand) {}

        @Override
        public void visitVarInsn(int opcode, int varIndex) {}

        @Override
        public void visitTypeInsn(int opcode, String type) {}

        @Override
        public void visitFieldInsn(int opcode, String owner, String name, String descriptor) {}

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {}

        @Override
        public void visitInvokeDynamicInsn(String name, String descriptor, Handle bootstrapMethodHandle, Object... bootstrapMethodArguments) {}

        @Override
        public void visitJumpInsn(int opcode, Label label) {}

        @Override
        public void visitLabel(Label label) {}

        @Override
        public void visitLdcInsn(Object value) {}

        @Override
        public void visitIincInsn(int varIndex, int increment) {}

        @Override
        public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) {}

        @Override
        public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) {}

        @Override
        public void visitMultiANewArrayInsn(String descriptor, int numDimensions) {}

        @Override
        public void visitFrame(int type, int numLocal, Object[] local, int numStack, Object[] stack) {}

        @Override
        public void visitTryCatchBlock(Label start, Label end, Label handler, String type) {}

        @Override
        public void visitLineNumber(int line, Label start) {}

        @Override
        public void visitLocalVariable(String name, String descriptor, String signature, Label start, Label end, int index) {}

        @Override
        public void visitMaxs(int maxStack, int maxLocals) {
            mv.visitMaxs(0, 0);
        }

        @Override
        public void visitEnd() {
            mv.visitEnd();
        }
    }

    /**
     * Rewrites SoundMechanic's constructor to avoid the broken Sound.values()/Enum::name lambda
     * on Paper 1.20.5+ where Sound is an interface. The original code:
     *
     *   if (Arrays.stream(Sound.values()).map(Enum::name).anyMatch(...)) {
     *       this.sound = Sound.valueOf(...);
     *   }
     *
     * is replaced with nothing, leaving this.sound as null. The cast() method already falls back
     * to playing the sound by string when this.sound is null.
     */
    private static class SoundMechanicInitRewriter extends MethodVisitor {

        private static final String LOCATION_MECHANIC = "io/lumine/mythic/lib/script/mechanic/type/LocationMechanic";
        private static final String CONFIG_OBJECT = "io/lumine/mythic/lib/util/configobject/ConfigObject";
        private static final String DOUBLE_FORMULA = "io/lumine/mythic/lib/util/DoubleFormula";
        private static final String SOUND_MECHANIC = "io/lumine/mythic/lib/script/mechanic/visual/SoundMechanic";

        public SoundMechanicInitRewriter(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitCode() {
            mv.visitCode();

            // super(config);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, LOCATION_MECHANIC, "<init>",
                    "(L" + CONFIG_OBJECT + ";)V", false);

            // config.validateKeys("sound");
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitInsn(Opcodes.ICONST_1);
            mv.visitTypeInsn(Opcodes.ANEWARRAY, "java/lang/String");
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_0);
            mv.visitLdcInsn("sound");
            mv.visitInsn(Opcodes.AASTORE);
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "validateKeys",
                    "([Ljava/lang/String;)V", true);

            // this.soundString = config.getString("sound");
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn("sound");
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "getString",
                    "(Ljava/lang/String;)Ljava/lang/String;", true);
            mv.visitFieldInsn(Opcodes.PUTFIELD, SOUND_MECHANIC, "soundString", "Ljava/lang/String;");

            // this.vol = config.getDoubleFormula("volume", DoubleFormula.constant(1.0));
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn("volume");
            mv.visitInsn(Opcodes.DCONST_1);
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, DOUBLE_FORMULA, "constant",
                    "(D)L" + DOUBLE_FORMULA + ";", false);
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "getDoubleFormula",
                    "(Ljava/lang/String;L" + DOUBLE_FORMULA + ";)L" + DOUBLE_FORMULA + ";", true);
            mv.visitFieldInsn(Opcodes.PUTFIELD, SOUND_MECHANIC, "vol", "L" + DOUBLE_FORMULA + ";");

            // this.pitch = config.getDoubleFormula("pitch", DoubleFormula.constant(1.0));
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn("pitch");
            mv.visitInsn(Opcodes.DCONST_1);
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, DOUBLE_FORMULA, "constant",
                    "(D)L" + DOUBLE_FORMULA + ";", false);
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "getDoubleFormula",
                    "(Ljava/lang/String;L" + DOUBLE_FORMULA + ";)L" + DOUBLE_FORMULA + ";", true);
            mv.visitFieldInsn(Opcodes.PUTFIELD, SOUND_MECHANIC, "pitch", "L" + DOUBLE_FORMULA + ";");

            mv.visitInsn(Opcodes.RETURN);
        }

        @Override
        public void visitInsn(int opcode) {}

        @Override
        public void visitIntInsn(int opcode, int operand) {}

        @Override
        public void visitVarInsn(int opcode, int varIndex) {}

        @Override
        public void visitTypeInsn(int opcode, String type) {}

        @Override
        public void visitFieldInsn(int opcode, String owner, String name, String descriptor) {}

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {}

        @Override
        public void visitInvokeDynamicInsn(String name, String descriptor, Handle bootstrapMethodHandle, Object... bootstrapMethodArguments) {}

        @Override
        public void visitJumpInsn(int opcode, Label label) {}

        @Override
        public void visitLabel(Label label) {}

        @Override
        public void visitLdcInsn(Object value) {}

        @Override
        public void visitIincInsn(int varIndex, int increment) {}

        @Override
        public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) {}

        @Override
        public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) {}

        @Override
        public void visitMultiANewArrayInsn(String descriptor, int numDimensions) {}

        @Override
        public void visitFrame(int type, int numLocal, Object[] local, int numStack, Object[] stack) {}

        @Override
        public void visitTryCatchBlock(Label start, Label end, Label handler, String type) {}

        @Override
        public void visitLineNumber(int line, Label start) {}

        @Override
        public void visitLocalVariable(String name, String descriptor, String signature, Label start, Label end, int index) {}

        @Override
        public void visitMaxs(int maxStack, int maxLocals) {
            mv.visitMaxs(4, 2);
        }

        @Override
        public void visitEnd() {
            mv.visitEnd();
        }
    }

    /**
     * Rewrites PlayerSoundMechanic's constructor the same way as SoundMechanic.
     */
    private static class PlayerSoundMechanicInitRewriter extends MethodVisitor {

        private static final String TARGET_MECHANIC = "io/lumine/mythic/lib/script/mechanic/type/TargetMechanic";
        private static final String CONFIG_OBJECT = "io/lumine/mythic/lib/util/configobject/ConfigObject";
        private static final String DOUBLE_FORMULA = "io/lumine/mythic/lib/util/DoubleFormula";
        private static final String PLAYER_SOUND_MECHANIC = "io/lumine/mythic/lib/script/mechanic/visual/PlayerSoundMechanic";

        public PlayerSoundMechanicInitRewriter(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitCode() {
            mv.visitCode();

            // super(config);
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitMethodInsn(Opcodes.INVOKESPECIAL, TARGET_MECHANIC, "<init>",
                    "(L" + CONFIG_OBJECT + ";)V", false);

            // config.validateKeys("sound");
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitInsn(Opcodes.ICONST_1);
            mv.visitTypeInsn(Opcodes.ANEWARRAY, "java/lang/String");
            mv.visitInsn(Opcodes.DUP);
            mv.visitInsn(Opcodes.ICONST_0);
            mv.visitLdcInsn("sound");
            mv.visitInsn(Opcodes.AASTORE);
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "validateKeys",
                    "([Ljava/lang/String;)V", true);

            // this.soundString = config.getString("sound");
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn("sound");
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "getString",
                    "(Ljava/lang/String;)Ljava/lang/String;", true);
            mv.visitFieldInsn(Opcodes.PUTFIELD, PLAYER_SOUND_MECHANIC, "soundString", "Ljava/lang/String;");

            // this.vol = config.getDoubleFormula("volume", DoubleFormula.constant(1.0));
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn("volume");
            mv.visitInsn(Opcodes.DCONST_1);
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, DOUBLE_FORMULA, "constant",
                    "(D)L" + DOUBLE_FORMULA + ";", false);
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "getDoubleFormula",
                    "(Ljava/lang/String;L" + DOUBLE_FORMULA + ";)L" + DOUBLE_FORMULA + ";", true);
            mv.visitFieldInsn(Opcodes.PUTFIELD, PLAYER_SOUND_MECHANIC, "vol", "L" + DOUBLE_FORMULA + ";");

            // this.pitch = config.getDoubleFormula("pitch", DoubleFormula.constant(1.0));
            mv.visitVarInsn(Opcodes.ALOAD, 0);
            mv.visitVarInsn(Opcodes.ALOAD, 1);
            mv.visitLdcInsn("pitch");
            mv.visitInsn(Opcodes.DCONST_1);
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, DOUBLE_FORMULA, "constant",
                    "(D)L" + DOUBLE_FORMULA + ";", false);
            mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, CONFIG_OBJECT, "getDoubleFormula",
                    "(Ljava/lang/String;L" + DOUBLE_FORMULA + ";)L" + DOUBLE_FORMULA + ";", true);
            mv.visitFieldInsn(Opcodes.PUTFIELD, PLAYER_SOUND_MECHANIC, "pitch", "L" + DOUBLE_FORMULA + ";");

            mv.visitInsn(Opcodes.RETURN);
        }

        @Override public void visitInsn(int opcode) {}
        @Override public void visitIntInsn(int opcode, int operand) {}
        @Override public void visitVarInsn(int opcode, int varIndex) {}
        @Override public void visitTypeInsn(int opcode, String type) {}
        @Override public void visitFieldInsn(int opcode, String owner, String name, String descriptor) {}
        @Override public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {}
        @Override public void visitInvokeDynamicInsn(String name, String descriptor, Handle bootstrapMethodHandle, Object... bootstrapMethodArguments) {}
        @Override public void visitJumpInsn(int opcode, Label label) {}
        @Override public void visitLabel(Label label) {}
        @Override public void visitLdcInsn(Object value) {}
        @Override public void visitIincInsn(int varIndex, int increment) {}
        @Override public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) {}
        @Override public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) {}
        @Override public void visitMultiANewArrayInsn(String descriptor, int numDimensions) {}
        @Override public void visitFrame(int type, int numLocal, Object[] local, int numStack, Object[] stack) {}
        @Override public void visitTryCatchBlock(Label start, Label end, Label handler, String type) {}
        @Override public void visitLineNumber(int line, Label start) {}
        @Override public void visitLocalVariable(String name, String descriptor, String signature, Label start, Label end, int index) {}
        @Override public void visitMaxs(int maxStack, int maxLocals) {
            mv.visitMaxs(4, 2);
        }
        @Override public void visitEnd() {
            mv.visitEnd();
        }
    }

    /**
     * Rewrites BukkitHologramFactory$HologramImpl.updateLocation() to use
     * Entity.teleportAsync(Location) instead of Entity.teleport(Location).
     * On Folia, synchronous teleport is not allowed from region threads.
     */
    private static class HologramTeleportRewriter extends MethodVisitor {

        private static final String ENTITY_PACKAGE = "org/bukkit/entity/";
        private static final String LOCATION_CLASS = "org/bukkit/Location";
        private static final String TELEPORT_ASYNC_DESC = "(L" + LOCATION_CLASS + ";)Ljava/util/concurrent/CompletableFuture;";

        public HologramTeleportRewriter(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {
            if ((opcode == Opcodes.INVOKEVIRTUAL || opcode == Opcodes.INVOKEINTERFACE)
                    && owner != null && owner.startsWith(ENTITY_PACKAGE)
                    && "teleport".equals(name)
                    && ("(L" + LOCATION_CLASS + ";)Z").equals(descriptor)) {
                mv.visitMethodInsn(Opcodes.INVOKEINTERFACE, owner, "teleportAsync",
                        TELEPORT_ASYNC_DESC, true);
                return;
            }
            mv.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
        }
    }

    /**
     * Generic rewriter that replaces Entity.teleport(Location) with Entity.teleportAsync(Location)
     * when the returned boolean is immediately discarded (POP). On Folia, synchronous teleport is
     * not allowed from region threads, while teleportAsync works everywhere. If the boolean return
     * value is used (no POP), the original teleport call is kept to avoid breaking control flow.
     */
    private static class EntityTeleportRewriter extends MethodVisitor {

        private static final String ENTITY_PACKAGE = "org/bukkit/entity/";
        private static final String LOCATION_CLASS = "org/bukkit/Location";
        private static final String TELEPORT_ASYNC_DESC = "(L" + LOCATION_CLASS + ";)Ljava/util/concurrent/CompletableFuture;";

        private boolean pendingTeleport = false;
        private int pendingOpcode;
        private String pendingOwner;
        private String pendingName;
        private String pendingDescriptor;
        private boolean pendingIsInterface;

        public EntityTeleportRewriter(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {
            flushPending();
            if ((opcode == Opcodes.INVOKEVIRTUAL || opcode == Opcodes.INVOKEINTERFACE)
                    && owner != null && owner.startsWith(ENTITY_PACKAGE)
                    && "teleport".equals(name)
                    && ("(L" + LOCATION_CLASS + ";)Z").equals(descriptor)) {
                pendingTeleport = true;
                pendingOpcode = opcode;
                pendingOwner = owner;
                pendingName = name;
                pendingDescriptor = descriptor;
                pendingIsInterface = isInterface;
                return;
            }
            super.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
        }

        @Override
        public void visitInsn(int opcode) {
            if (pendingTeleport) {
                pendingTeleport = false;
                if (opcode == Opcodes.POP) {
                    // Replace teleport with teleportAsync; the original POP discards the returned CompletableFuture.
                    super.visitMethodInsn(Opcodes.INVOKEINTERFACE, pendingOwner, "teleportAsync",
                            TELEPORT_ASYNC_DESC, true);
                    super.visitInsn(opcode);
                    return;
                }
                // The return value is actually used; keep the original teleport call.
                super.visitMethodInsn(pendingOpcode, pendingOwner, pendingName, pendingDescriptor, pendingIsInterface);
                super.visitInsn(opcode);
                return;
            }
            super.visitInsn(opcode);
        }

        @Override public void visitIntInsn(int opcode, int operand) { flushPending(); super.visitIntInsn(opcode, operand); }
        @Override public void visitVarInsn(int opcode, int varIndex) { flushPending(); super.visitVarInsn(opcode, varIndex); }
        @Override public void visitTypeInsn(int opcode, String type) { flushPending(); super.visitTypeInsn(opcode, type); }
        @Override public void visitFieldInsn(int opcode, String owner, String name, String descriptor) { flushPending(); super.visitFieldInsn(opcode, owner, name, descriptor); }
        @Override public void visitInvokeDynamicInsn(String name, String descriptor, Handle bootstrapMethodHandle, Object... bootstrapMethodArguments) { flushPending(); super.visitInvokeDynamicInsn(name, descriptor, bootstrapMethodHandle, bootstrapMethodArguments); }
        @Override public void visitJumpInsn(int opcode, Label label) { flushPending(); super.visitJumpInsn(opcode, label); }
        @Override public void visitLabel(Label label) { flushPending(); super.visitLabel(label); }
        @Override public void visitLdcInsn(Object value) { flushPending(); super.visitLdcInsn(value); }
        @Override public void visitIincInsn(int varIndex, int increment) { flushPending(); super.visitIincInsn(varIndex, increment); }
        @Override public void visitTableSwitchInsn(int min, int max, Label dflt, Label... labels) { flushPending(); super.visitTableSwitchInsn(min, max, dflt, labels); }
        @Override public void visitLookupSwitchInsn(Label dflt, int[] keys, Label[] labels) { flushPending(); super.visitLookupSwitchInsn(dflt, keys, labels); }
        @Override public void visitMultiANewArrayInsn(String descriptor, int numDimensions) { flushPending(); super.visitMultiANewArrayInsn(descriptor, numDimensions); }
        @Override public void visitFrame(int type, int numLocal, Object[] local, int numStack, Object[] stack) { flushPending(); super.visitFrame(type, numLocal, local, numStack, stack); }
        @Override public void visitTryCatchBlock(Label start, Label end, Label handler, String type) { flushPending(); super.visitTryCatchBlock(start, end, handler, type); }
        @Override public void visitLineNumber(int line, Label start) { flushPending(); super.visitLineNumber(line, start); }
        @Override public void visitLocalVariable(String name, String descriptor, String signature, Label start, Label end, int index) { flushPending(); super.visitLocalVariable(name, descriptor, signature, start, end, index); }
        @Override public void visitMaxs(int maxStack, int maxLocals) { flushPending(); super.visitMaxs(maxStack, maxLocals); }
        @Override public void visitEnd() { flushPending(); super.visitEnd(); }

        private void flushPending() {
            if (pendingTeleport) {
                super.visitMethodInsn(pendingOpcode, pendingOwner, pendingName, pendingDescriptor, pendingIsInterface);
                pendingTeleport = false;
            }
        }
    }

    /**
     * Rewrites MMOPlayerData.forEach/forEachPlaying/forEachOnline to dispatch each
     * Consumer.accept(data) call to that player's owning region thread. This makes MythicLib's
     * global player-data tickers (tickPlaying, tickOnline, passive skills, mana, etc.) Folia-safe.
     */
    private static class MMOPlayerDataForEachRewriter extends MethodVisitor {

        private static final String CONSUMER_CLASS = "java/util/function/Consumer";
        private static final String HELPER_CLASS = "top/mcocet/mMOAddon/foliafix/common/SchedulerHelper";
        private static final String MYTHICLIB_CLASS = "io/lumine/mythic/lib/MythicLib";

        public MMOPlayerDataForEachRewriter(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {
            if (opcode == Opcodes.INVOKEINTERFACE
                    && CONSUMER_CLASS.equals(owner)
                    && "accept".equals(name)
                    && "(Ljava/lang/Object;)V".equals(descriptor)) {
                mv.visitFieldInsn(Opcodes.GETSTATIC, MYTHICLIB_CLASS, "plugin", "Lio/lumine/mythic/lib/MythicLib;");
                mv.visitMethodInsn(Opcodes.INVOKESTATIC, HELPER_CLASS, "acceptOnPlayerRegion",
                        "(Ljava/util/function/Consumer;Ljava/lang/Object;Lorg/bukkit/plugin/Plugin;)V", false);
                return;
            }
            super.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
        }
    }

    private static class SchedulerMethodVisitor extends MethodVisitor {

        public SchedulerMethodVisitor(MethodVisitor mv) {
            super(Opcodes.ASM9, mv);
        }

        @Override
        public void visitMethodInsn(int opcode, String owner, String name, String descriptor, boolean isInterface) {
            // Replace Bukkit.getScheduler() -> SchedulerHelper.getScheduler()
            if (opcode == Opcodes.INVOKESTATIC
                    && owner.equals(BUKKIT_CLASS)
                    && name.equals("getScheduler")
                    && descriptor.equals("()L" + BUKKIT_SCHEDULER_CLASS + ";")) {
                schedulerPatchCount++;
                mv.visitMethodInsn(Opcodes.INVOKESTATIC, HELPER_CLASS, "getScheduler",
                        "()L" + BUKKIT_SCHEDULER_CLASS + ";", false);
                return;
            }

            // Patch BukkitRunnable.runXxx(plugin, ...) calls.
            // Subclasses and anonymous inner classes may reference the inherited method
            // through their own type rather than BukkitRunnable, so match by name/descriptor.
            if (opcode == Opcodes.INVOKEVIRTUAL && tryPatchBukkitRunnableCall(name, descriptor)) {
                return;
            }

            // Patch BukkitRunnable.cancel() -> SchedulerHelper.cancelBukkitRunnable(this)
            // on BukkitRunnable itself or on subclasses from any active target plugin.
            if (opcode == Opcodes.INVOKEVIRTUAL
                    && name.equals("cancel")
                    && descriptor.equals("()V")
                    && (owner.equals(BUKKIT_RUNNABLE_CLASS) || isActiveTargetOwner(owner))) {
                mv.visitMethodInsn(Opcodes.INVOKESTATIC, HELPER_CLASS, "cancelBukkitRunnable",
                        "(L" + BUKKIT_RUNNABLE_CLASS + ";)V", false);
                return;
            }

            // Replace Sound.valueOf(String) with SchedulerHelper.resolveSound(String).
            // On Paper 1.20.5+ Sound is an interface and has no valueOf method.
            // The helper throws IllegalArgumentException so callers' try/catch fall back to string keys.
            if (opcode == Opcodes.INVOKESTATIC
                    && owner.equals("org/bukkit/Sound")
                    && name.equals("valueOf")
                    && descriptor.equals("(Ljava/lang/String;)Lorg/bukkit/Sound;")) {
                mv.visitMethodInsn(Opcodes.INVOKESTATIC, HELPER_CLASS, "resolveSound",
                        "(Ljava/lang/String;)Lorg/bukkit/Sound;", false);
                return;
            }

            mv.visitMethodInsn(opcode, owner, name, descriptor, isInterface);
        }

        private boolean tryPatchBukkitRunnableCall(String name, String descriptor) {
            String expectedDescriptor;
            String helperDescriptor;
            switch (name) {
                case "runTask":
                    expectedDescriptor = "(Lorg/bukkit/plugin/Plugin;)Lorg/bukkit/scheduler/BukkitTask;";
                    helperDescriptor = "(L" + BUKKIT_RUNNABLE_CLASS + ";Lorg/bukkit/plugin/Plugin;)Lorg/bukkit/scheduler/BukkitTask;";
                    break;
                case "runTaskLater":
                    expectedDescriptor = "(Lorg/bukkit/plugin/Plugin;J)Lorg/bukkit/scheduler/BukkitTask;";
                    helperDescriptor = "(L" + BUKKIT_RUNNABLE_CLASS + ";Lorg/bukkit/plugin/Plugin;J)Lorg/bukkit/scheduler/BukkitTask;";
                    break;
                case "runTaskTimer":
                    expectedDescriptor = "(Lorg/bukkit/plugin/Plugin;JJ)Lorg/bukkit/scheduler/BukkitTask;";
                    helperDescriptor = "(L" + BUKKIT_RUNNABLE_CLASS + ";Lorg/bukkit/plugin/Plugin;JJ)Lorg/bukkit/scheduler/BukkitTask;";
                    break;
                case "runTaskAsynchronously":
                    expectedDescriptor = "(Lorg/bukkit/plugin/Plugin;)Lorg/bukkit/scheduler/BukkitTask;";
                    helperDescriptor = "(L" + BUKKIT_RUNNABLE_CLASS + ";Lorg/bukkit/plugin/Plugin;)Lorg/bukkit/scheduler/BukkitTask;";
                    break;
                case "runTaskLaterAsynchronously":
                    expectedDescriptor = "(Lorg/bukkit/plugin/Plugin;J)Lorg/bukkit/scheduler/BukkitTask;";
                    helperDescriptor = "(L" + BUKKIT_RUNNABLE_CLASS + ";Lorg/bukkit/plugin/Plugin;J)Lorg/bukkit/scheduler/BukkitTask;";
                    break;
                case "runTaskTimerAsynchronously":
                    expectedDescriptor = "(Lorg/bukkit/plugin/Plugin;JJ)Lorg/bukkit/scheduler/BukkitTask;";
                    helperDescriptor = "(L" + BUKKIT_RUNNABLE_CLASS + ";Lorg/bukkit/plugin/Plugin;JJ)Lorg/bukkit/scheduler/BukkitTask;";
                    break;
                default:
                    return false;
            }

            if (!descriptor.equals(expectedDescriptor)) {
                return false;
            }

            bukkitRunnablePatchCount++;
            mv.visitMethodInsn(Opcodes.INVOKESTATIC, HELPER_CLASS, name, helperDescriptor, false);
            return true;
        }
    }
}
